### ISSUE TITLE
Help! This plugin killed my blog

### ISSUE THREAD

**Issue by PedroFumero** [maximeschoeni/sublanguage#16]
Hello, I was install this plugin, and I removed, after when I try to enter on any post, this redirects me to index ¿How can I solve this issue?  

Can you check please? http://pedrofumero.com/

**Comment by maximeschoeni** [comment]
Hello, this is probably a problem with your permalinks. Go to Settings > Permalinks and click "Save changes".

**Comment by PedroFumero** [comment]
Thanks a lot @maximeschoeni this has solved it
