### ISSUE TITLE
Version 2 doesn't work

### ISSUE THREAD

**Issue by laiaquixalos** [maximeschoeni/sublanguage#21]
Hi, 
I've installed the las version of wordpress and the last version of sublanguage and doesn't work.
Menus doesn't keep the language.
When i active the permanent links with the entry name option, doesn't find the pages.
I have used it in other ocasions with older version and i didn't have any problems.

**Comment by maximeschoeni** [comment]
Hi, thnx for report. What is your version of PHP?

**Comment by laiaquixalos** [comment]
Hi!
PHP Version 5.6.30.
Thanks.

**Comment by maximeschoeni** [comment]
When you activated Sublanguage, was your admin language other than english? If so please verify the value of the "locale" box in each language (should be something like 'fr_FR', it_IT', etc. Just US english should be empty).

**Comment by laiaquixalos** [comment]
Hi maximeschoeni,
Sorry to bother you, I think the problem is with my server cause they have changed from Apache to nginx and the permalinks are not working properly. Is not a problem with your plugin.
Thanks for all.

**Comment by maximeschoeni** [comment]
Actually I think it is :) I just found a bug that can cause the problem you described... I am going to fix it quick.

**Comment by maximeschoeni** [comment]
I just released a new version patching a few bugs. Would you like to have a try to see if it works better? Please download the last version from Github.

**Comment by laiaquixalos** [comment]
Hi, I've tried now and it works perfectly.
Thank you very much! :)

**Comment by maximeschoeni** [comment]
Great!
