### ISSUE TITLE
Translate post but not post permalinks

### ISSUE THREAD

**Issue by shererere** [maximeschoeni/sublanguage#27]
Hello, I've made a permalink structure like `/product_category/product_name` (just by using wordpress). I needed to translate all the products, so I installed sublanguage. The problem is, it overwrites the. Is it possible to translate the post content and name but not the permalink?

**Comment by maximeschoeni** [comment]
Hello, Sure. In the wp admin you can go in "Products > Language options" then uncheck "post_name" in the "Tanslatable post fields" section (permalink is built from "post_name" field)

**Comment by shererere** [comment]
Not exactly what I've meant. I want to translate the name, but dont want Sublanguage to overwrite the permalink.

**Comment by maximeschoeni** [comment]
I guess you can't do that... But why do you need a translated name if it isn't for permalinks?
