### ISSUE TITLE
HTML code in translate_options variables ?

### ISSUE THREAD

**Issue by kernel23** [maximeschoeni/sublanguage#3]
Hi again,

When using the translate_options page to translate raw variable, i need to use text containing basic HTML (like HREF code). If i use the form from sublanguage, my string are converted in full HTML : 

> &amp;lt;a href=&amp;quot;/&amp;quot;&amp;gt;

This is confusing as original Wordpress Customizer and some plugins (ie Widget text) allow HTML code.

Thanks.

**Comment by maximeschoeni** [comment]
Hello,

Thank you for pointing this issue. I just committed a few changes to fixe it.

**Comment by kernel23** [comment]
Thanks it works !
