### ISSUE TITLE
Read more tag does not work on translation

### ISSUE THREAD

**Issue by dbrw** [maximeschoeni/sublanguage#4]
Hi, I just use sublanguange and it is a great plugin. But there is a problem if I use `the_content();` on my archive template, the translated content does not truncated by `<!--more-->` tag. Is there anybody experiencing this situation, do You have any solution for this?

**Comment by maximeschoeni** [comment]
Hello, 

Thank you for pointing out this bug. I just uploaded a release to fix it. Please tell me if it is working now.

**Comment by dbrw** [comment]
Hi, I just check it and now it's work. Great job!
