### ISSUE TITLE
Problem with AJAX - wrong language

### ISSUE THREAD

**Issue by GasparSukk** [maximeschoeni/sublanguage#56]
Wordpress: 5.6.2
Sublanguage: 2.7.1
Main/default language: et
Alternate language: en (locale en_US)

I have a post in other language:
https://domain.domain/en/my-post
**It has correct content. OK.**

I ask the same post by AJAX, passing language (tried both the slug and locale):
```
$.get(AJAX_URL, {
	'action': 'load_posts_by_ajax',
	'post': 'MY_POST_ID',
	'language': 'en'
});
```
**Content is in default language. WRONG.**

**Comment by maximeschoeni** [comment]
Hello,
The problem probably lies in your ajax handler. It looks probably like this:


    $id = $_GET['post'];
    $post = get_post($id);
    echo json_encode($post);
    exit;

The problem here is that `get_post()` won't translate anything. Instead you must use a WP loop:

    $id = $_GET['post'];

    $query = new WP_Query(array(
      'p' => $id
    ));

    while ($query->have_posts()) {
      $query->the_post();
      echo json_encode($query->post);
      break;
    } 
    wp_reset_postdata();

    exit;

**Comment by GasparSukk** [comment]
I used get_post() and changed to LOOP.
No changes - the post is still untranslated.

I tried to switch off permalinks to see the logic.
Problem is same - page is correct then i view it directly: https://domain.com/?p=1234&language=en
Then i get it by ajax the language is ignored.

How is your plugin detects language?

**Comment by maximeschoeni** [comment]
Im not sure if your problem comes from the language detection or translation.

can you add the following in your template (the one that is called by ajax request) to check what it is?

    global $sublanguage;
    var_dump($sublanguage->current_language->post_title);

**Comment by GasparSukk** [comment]
Results:
1) object page direct display - ENG
2) object page with AJAX - NULL

**Comment by GasparSukk** [comment]
Bump.

Any news?

**Comment by GasparSukk** [comment]
I finally found the problem. I passed locale to AJAX, not language. Passing language fixed the problem!
