### ISSUE TITLE
Translate Custom Fields

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [maximeschoeni/sublanguage#58]
Is it possible to translate custom fields? Either ACF? Or fields appearing in the sidebar (e.g. Secondary Subtitle plugin)

**Comment by maximeschoeni** [comment]
Hello, sure you can translate them. You just need to go in sublanguage settings, click on the link "options" after the post-type, and check the checkbox corresponding to your ACF key (not the one starting width "_") under "Translatable post meta". If you're using gutenberg you also need to uncheck "Use asynchronous language switch in Gutenberg". But actually it isn't working very good with Gutenberg, I need to improve it.

**Comment by mariomurrent-softwaresolutions** [comment]
Awesome thx :) I did not see that option ... it a bit hidden

**Comment by mariomurrent-softwaresolutions** [comment]
@maximeschoeni Yes, sometimes when I save the English translation and switch back to German then the German text is English :( ...

What does this "Use asynchronous language switch in Gutenberg" do? I already disabled it

**Comment by maximeschoeni** [comment]
It allows to change language without reloading the page... But as you saw it doesn't work well (even if you actually disabled it). Gutenberg is a pain to work with :(

**Comment by mariomurrent-softwaresolutions** [comment]
Okay, so there will be no update for the future? Will you stop working on this one?

**Comment by maximeschoeni** [comment]
No I'm going to fixe this soon because I need it fixed for my own works.

**Comment by mariomurrent-softwaresolutions** [comment]
Okay :) Let me know, when this is fixed ... thx

**Comment by maximeschoeni** [comment]
Ok I did the fix. Just update the plugin in wp or download the new release from here or from  https://wordpress.org/plugins/sublanguage/

Unfortunately there is still a problem I couldn't manage to solve: when you leave the editor page you're always getting the popup alert saying your changes haven't been saved even if you just clicked the update button...

**Comment by mariomurrent-softwaresolutions** [comment]
Okay well I can deal with that 😊 at least it's good when the async stuff is working with the custom fields
